<a href="https://colab.research.google.com/github/LinglinNero/MSSP607/blob/main/Pacticipation_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#connect to github file
from google.colab import userdata
import os

github_token = userdata.get('Git_Hub')
owner = 'LinglinNero' # Replace with the GitHub repository owner
repository = 'MSSP607' # Replace with the GitHub repository name

clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'

# Clone the repository
!git clone {clone_url}

Cloning into 'MSSP607'...
remote: Enumerating objects: 162, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 162 (delta 69), reused 34 (delta 17), pack-reused 0 (from 0)
Receiving objects: 100% (162/162), 7.24 MiB | 5.88 MiB/s, done.
Resolving deltas: 100% (69/69), done.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import os
import numpy as np

In [15]:
#2.b Read each file into a dataframe
appl = pd.read_csv('/content/MSSP607/data/data/aapl.csv')
amzn = pd.read_csv('/content/MSSP607/data/data/amzn.csv')
fb = pd.read_csv('/content/MSSP607/data/data/fb.csv')
goog = pd.read_csv('/content/MSSP607/data/data/goog.csv')
nflx = pd.read_csv('/content/MSSP607/data/data/nflx.csv')

In [17]:
#2.c
appl['ticker'] = 'APPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

In [19]:
#2.d
all_data = pd.concat([appl, amzn, fb, goog, nflx])

In [7]:
#2.e
all_data.to_csv('/content/MSSP607/data/data/faanf.csv', index=False)

In [8]:
#2.f
faanf = pd.read_csv('/content/MSSP607/data/data/faanf.csv')
faanf['date'] = pd.to_datetime(faanf['date'])
faanf['volume'] = faanf['volume'].astype(int)
faanf.sort_values(by = ['date','ticker'])

           date       open       high        low      close    volume ticker
251  2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   amzn
0    2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   appl
502  2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     fb
753  2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   goog
1004 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   nflx
...         ...        ...        ...        ...        ...       ...    ...
501  2018-12-31  1510.8000  1520.7600  1487.0000  1501.9700   6954507   amzn
250  2018-12-31   157.8529   158.6794   155.8117   157.0663  35003466   appl
752  2018-12-31   134.4500   134.6400   129.9500   131.0900  24625308     fb
1003 2018-12-31  1050.9600  1052.7000  1023.5900  1035.6100   1493722   goog
1254 2018-12-31   260.1600   270.1001   260.0000   267.6600  13508920   nflx

[1255 rows x 7 columns]

In [9]:
#2.g
top_7 = faanf.nlargest(7,'volume')
top_7

          date      open      high       low     close     volume ticker
644 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     fb
555 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     fb
559 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     fb
556 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     fb
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   appl
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   appl
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   appl

In [10]:
#2.h
faanf_melted = pd.melt(faanf, id_vars=['date', 'ticker'],
                       var_name='variable',
                       value_name='value')
faanf_melted

           date ticker variable         value
0    2018-01-02   appl     open  1.669271e+02
1    2018-01-03   appl     open  1.692521e+02
2    2018-01-04   appl     open  1.692619e+02
3    2018-01-05   appl     open  1.701448e+02
4    2018-01-08   appl     open  1.710375e+02
...         ...    ...      ...           ...
6270 2018-12-24   nflx   volume  9.547616e+06
6271 2018-12-26   nflx   volume  1.440274e+07
6272 2018-12-27   nflx   volume  1.223522e+07
6273 2018-12-28   nflx   volume  1.098729e+07
6274 2018-12-31   nflx   volume  1.350892e+07

[6275 rows x 4 columns]