<a href="https://colab.research.google.com/github/LinglinNero/MSSP607/blob/main/PARTICIPATION_ACTIVITY_Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

Mounted at /content/drive

In [3]:
file_path = '/content/drive/MyDrive/MSSP607/Modules/Module4/parsed.csv'
df = pd.read_csv(file_path)
df['mag'] = pd.to_numeric(df['mag'], errors='coerce')
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [4]:
#a. Find the 95th percentile of earthquake magnitude in Japan using magType of 'mb'
place_Japan = df['place'].str.contains('Japan', na = False)
magType_mb = df['magType'] == 'mb'
Japan_mb_earthquake = df[place_Japan & magType_mb]
magnitude = Japan_mb_earthquake['mag']
percentile_95 = np.percentile(magnitude, 95)
percentile_95_formatted = float(percentile_95)
print(percentile_95_formatted)

4.9

In [5]:
#b. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.
place_indonesia = df['place'].str.contains('Indonesia', na = False)
indonesia_earthquake = df[place_indonesia]
indonesia_earthquake_count = len(indonesia_earthquake)
tsunami = df['tsunami'] == 1
indonesia_tsunami = df[place_indonesia & tsunami]
indonesia_tsunami_count = len(indonesia_tsunami)
percentage = (indonesia_tsunami_count / indonesia_earthquake_count)
percentage_formatted = float(percentage)
print(percentage_formatted)

0.23129251700680273

In [6]:
#c. Get summary statistics for earthquakes in Nevada
place_nevada = df['place'].str.contains('Nevada', na = False)
nevada_earthquake = df[place_nevada]
nevada_earthquake.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,677.000000,15.000000,677.000000,677.000000,1.00,677.000000,677.000000,677.000000,6.770000e+02,677.0,677.0,6.770000e+02
mean,2.440000,0.166982,2.400000,154.029527,0.491728,2.84,12.608567,0.151909,10.688331,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166400,4.626013,68.769713,0.689560,NaN,9.890620,0.084742,19.252727,5.954070e+08,0.0,0.0,6.000267e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.054000,1.000000,97.670000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.113000,1.000000,149.550000,0.400000,2.84,9.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.234000,1.000000,200.470000,0.900000,2.84,16.000000,0.186700,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [22]:
#d. Add a column to the dataframe indicating whether or not the earthquake happened in a country or US state that is on the Ring of Fire. Use Bolivia, Chile, Ecuador, Peru, Costa Rica, Guatemala, Mexico (be sure not to select New Mexico), Japan, Philippines, Indonesia, New Zealand, Antarctica (look for the Antarctic), Canada, Fiji, Alaska, Washington, California, Russia, Taiwan, Tonga, and the Kermadec Islands).
ring_of_fire = ['Bolivia', 'Chile', 'Ecuador', 'Peru', 'Costa Rica',
                'Guatemala', 'Mexico', 'Japan', 'Philippines', 'Indonesia', 'New Zealand',
                'Antarctic', 'Canada', 'Fiji', 'Alaska', 'Washington', 'California', 'Russia', 'Taiwan',
                'Tonga', 'Kermadec Islands'
]
search_method = '|'.join(ring_of_fire)
is_ring_of_fire = df['place'].str.contains(search_method, na = False, case=False)
is_new_mexico = df['place'].str.contains('New Mexico', na = False, case=False)
df['Ring_of_Fire'] = is_ring_of_fire & ~ is_new_mexico
df[is_new_mexico].head()
df.to_csv('earthquakes_with_ring_of_fire.csv', index=False)

In [23]:
#e. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them
ring_of_fire_count = df['Ring_of_Fire'].sum()
outside = len(df) - ring_of_fire_count
print(ring_of_fire_count)
print(outside)

4426
4906

In [19]:
#f. Find the tsunami count along the Ring of Fire
is_ring_of_fire_true = df['Ring_of_Fire'] == True
ring_of_fire_earthquakes = df[is_ring_of_fire_true]
tsunami_count = ring_of_fire_earthquakes['tsunami'].sum()
print(tsunami_count)

43